server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  port: 8080
  servlet:
    context-path: /library/api


spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:

      max-request-size: 5MB # for file upload
      max-file-size: 5MB # for file upload

  mvc:
    path match:
      matching-strategy: ant_path_matcher



backendapi:
  app:
    jwtSecret: librarySecretKey
    jwtExpirationMs: 86400000

logging:
  file:
    name: logs/library.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.org]': INFO
    '[org.hibernate]': INFO
    '[com.library]': DEBUG
